apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bkqh5isok-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bkqh5isok-go 
  name: bkqh5isok-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bkqh5isok-go 
